name: Continuous Integration

"on":
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules for theme)
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node (for linters/scripts)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install markdown linter
        run: npm i -g markdownlint-cli@0.41.0

      - name: Checking syntax mistakes in markdown
        run: |
          markdownlint "**/*.md" "**/*.mdx" \
            -c .github/workflow_configs/markdownlint.yml || true

      - name: Install yaml linter
        run: pipx install yamllint || pip install --user yamllint

      - name: Checking syntax mistakes in yaml
        run: |
          yamllint -d \
            "{extends: default, rules: {document-start: disable}}" -s \
             .github/workflows

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.128.2"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Link check (Markdown + built HTML)
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --verbose
            --no-progress
            --exclude-mail
            --accept 200,206,429
            "**/*.md" "public/**/*.html"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
